### ISSUE TITLE
Settings show when hovering on user in discussion

### ISSUE THREAD

**Issue by dav-is** [dav-is/flarum-ext-socialprofile#17]
See: https://nefald.fr/forum/d/4260-kempatshi

**Comment by dav-is** [comment]
Caused because user is not logged in.

**Comment by dsevillamartin** [comment]
I think this also lets you update the users setting, it didn't say "not allowed" or anything...
This is really serious!

**Comment by dav-is** [comment]
@datitisev It doesn't allow editing. It's not that serious

**Comment by dsevillamartin** [comment]
Oh ok, because it didn't give me an error when I click submit or save, I thought it did.
I didn't change anything, so maybe that was why :/
