### ISSUE TITLE
As signature

### ISSUE THREAD

**Issue by luceos** [dav-is/flarum-ext-socialprofile#3]
Discussable, but would love to have the option in the settings (and globally in the admin) to put the icons as signature on each post.

**Comment by dav-is** [comment]
Originally, the icons showed up when hovering over user's names. There seems to be an issue with 'm.redraw()' with that element and it doesn't reload that data. It used to work when it didn't need to fetch data.

**Comment by luceos** [comment]
Ah well i meant within the Post component, not in the User hover thing ;)

**Comment by dav-is** [comment]
I think that having the icons available inside the user's card is comparable to a signature. Closing because of this.
